## Practical No.2 : Write a NumPy program to implement following operation
### • to convert a list of numeric values into a one-dimensional NumPy array

In [1]:
# Name : Kishan Lashkari
# Enrollment : 216270307002

import numpy  

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]  

arr = numpy.array(a) 

print ("List: ", a) 

print ("Array: ", arr)

List:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Array:  [1 2 3 4 5 6 7 8 9]


### • to create a 3x3 matrix with values ranging from 2 to 10

In [2]:
# Name : Kishan Lashkari
# Enrollment : 216270307002

import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10])

newarr = arr.reshape(3, 3)

print(newarr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### • to append values at the end of an array

In [3]:
# Name : Kishan Lashkari
# Enrollment : 216270307002

import numpy as np

arr = np.array([10, 15, 20, 25])
print('Original Array : ', arr)

arr = np.append(arr, [30])
print('Array after appending : ', arr)

Original Array :  [10 15 20 25]
Array after appending :  [10 15 20 25 30]


### • to create another shape from an array without changing its data (3 * 2 to 2 * 3)

In [4]:
# Name : Kishan Lashkari
# Enrollment : 216270307002

import numpy as np

x = np.array([10, 20, 30, 40, 50, 60])
y = np.reshape(x, (3, 2))

print("Reshape 3x2 :")
print(y)

z = np.reshape(x, (2, 3))
print("Reshape 2x3 :")
print(z)

Reshape 3x2 :
[[10 20]
 [30 40]
 [50 60]]
Reshape 2x3 :
[[10 20 30]
 [40 50 60]]
